# Generated by Django 6.0.4 on 2026-04-22 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Directors', '0002_directors_directorimage'),
        ('Movies', '0001_initial'),
        ('actors', '0003_actor_actorimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtubeLink', models.URLField()),
                ('description', models.TextField()),
                ('releaseDate', models.DateField()),
                ('musicDirector', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('thumbnailImage', models.ImageField(blank=True, null=True, upload_to='trailers/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailers', to='Directors.directors')),
                ('leadActors', models.ManyToManyField(blank=True, related_name='trailers', to='actors.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='Movies.movies')),
            ],
        ),
    ]
