# Generated by Django 6.0.4 on 2026-04-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorName', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('designations', models.CharField(max_length=100)),
                ('noOfMovies', models.PositiveIntegerField()),
                ('debutMovie', models.CharField(max_length=100)),
                ('latestMovie', models.CharField(max_length=100)),
                ('upcomingMovie', models.CharField(max_length=100)),
                ('hits', models.PositiveIntegerField()),
                ('blockbusters', models.PositiveIntegerField()),
                ('averageMovies', models.PositiveIntegerField()),
                ('shortDescription', models.TextField()),
                ('since', models.PositiveIntegerField()),
                ('awards', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
