# Generated by Django 6.0.4 on 2026-04-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directors',
            name='directorImage',
            field=models.ImageField(blank=True, null=True, upload_to='directors/'),
        ),
    ]
