# Generated by Django 6.0.4 on 2026-04-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actorName', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('designation', models.CharField(max_length=300)),
                ('noOfMovies', models.PositiveIntegerField()),
                ('debutMovies', models.PositiveIntegerField()),
                ('latestMovie', models.CharField(max_length=100)),
                ('upcomingMovie', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('shortDescription', models.CharField(max_length=300)),
                ('noOfHits', models.PositiveIntegerField()),
                ('blockBusters', models.PositiveIntegerField()),
                ('averageMovies', models.PositiveIntegerField()),
                ('since', models.PositiveIntegerField()),
                ('awards', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
