# Generated by Django 6.0.4 on 2026-04-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='designation',
            new_name='designations',
        ),
        migrations.AlterField(
            model_name='actor',
            name='debutMovies',
            field=models.CharField(max_length=100),
        ),
    ]
