# Generated by Django 6.0.4 on 2026-04-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_rename_designation_actor_designations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actorImage',
            field=models.ImageField(blank=True, null=True, upload_to='actors/'),
        ),
    ]
