# Generated by Django 6.0.4 on 2026-04-22 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Directors', '0002_directors_directorimage'),
        ('OTTPlatform', '0002_ottplatform_ottlogo'),
        ('actors', '0003_actor_actorimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=150)),
                ('musicDirector', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('distributor', models.CharField(max_length=100)),
                ('satelliteRightsOwnedBy', models.CharField(max_length=100)),
                ('imdbRating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reviews', models.TextField()),
                ('releaseDate', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('shortDescription', models.TextField()),
                ('posterImage', models.ImageField(blank=True, null=True, upload_to='movies/posters/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('cast', models.ManyToManyField(blank=True, related_name='cast_movies', to='actors.actor')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_movies', to='Directors.directors')),
                ('hero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_movies', to='actors.actor')),
                ('ott', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='OTTPlatform.ottplatform')),
            ],
        ),
    ]
